// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {runtime} from '../models';

export function GetYTtrack(arg1:string):Promise<main.Result>;

export function Greet(arg1:string):Promise<string>;

export function WailsInit(arg1:runtime.Runtime):Promise<Error>;
