// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetYTtrack(arg1) {
  return window['go']['main']['App']['GetYTtrack'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function WailsInit(arg1) {
  return window['go']['main']['App']['WailsInit'](arg1);
}
